# docker-compose.yml
version: "3"
services:
  wasp-thing-service-postgres-testing:
    container_name: wasp-thing-service-postgres-testing
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=things
