apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wasp-thing-service.fullname" . }}-config
  labels:
    {{- include "wasp-thing-service.labels" . | nindent 4 }}
data:
  waspThingServicePort: {{ .Values.config.waspThingServicePort | quote }}
  dbHost: {{ include "wasp-thing-service.postgresql.fullname" . }}
  dbPort: {{ .Values.config.dbPort | quote }}
  dbName: {{ .Values.config.dbName }}
