apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wasp-thing-service.fullname" . }}-secret
  labels:
    {{- include "wasp-thing-service.labels" . | nindent 4 }}
data:
  jwtSecret: {{ .Values.config.jwtSecret | b64enc | quote }}
  dbPassword: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  dbUsername: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
